[build]
  base = "./"                          # Define the base directory (where the project is located)
  publish = "./"  # Directory where the built Angular app is located
  command = "ng build --prod"          # Build command for Angular

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
