[build]
  base = "./"                          # Define the base directory (where the project is located)
  publish = "./"  # Directory where the built Angular app is located
  command = "ng serve"          # Build command for Angular
